### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by M0gibear** [sophos/Sophos-Central-SIEM-Integration#15]
Getting a HTTP Error 500. I had previously tested pulling down logs with no error, but now we are getting this Internal Server Error.

> Error during request. Error code: 500, Error message:
> Traceback (most recent call last):
>   File "siem.py", line 476, in <module>
>     main()
>   File "siem.py", line 190, in main
>     process_endpoint(endpoint, opener, endpoint_config, token)
>   File "siem.py", line 223, in process_endpoint
>     write_json_format(results, siem_logger)
>   File "siem.py", line 257, in write_json_format
>     for i in results:
>   File "siem.py", line 327, in call_endpoint
>     events_response = request_url(opener, events_request)
>   File "siem.py", line 385, in request_url
>     response = opener.open(request)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
>     response = meth(req, response)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
>     return self._call_chain(*args)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
>     result = func(*args)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
>     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
> urllib2.HTTPError: HTTP Error 500: Internal Server Error

**Comment by M0gibear** [comment]
Looks like logs are pulling down again. Possibly Sophos server issue?
/shrug
