### ISSUE TITLE
Sometimes data comes as different type instead of <unicode>

### ISSUE THREAD

**Issue by srinathman** [sophos/Sophos-Central-SIEM-Integration#3]
Data always come as "unicode" type in the format_extension method. 
When debugging  with this code:
```
print type(data)
print data
```

We usually get an output like this for every field:
> <type 'unicode'>
> d98e9a76-878e-42cc-9e93-72f410df7863

But sometimes data comes as different type and causes a Type Error:

```
<type 'int'>
1484926007817
Traceback (most recent call last):
  File "./siem.py", line 539, in <module>
    main()
  File "./siem.py", line 209, in main
    process_endpoint(endpoint, opener, endpoint_config, creds)
  File "./siem.py", line 267, in process_endpoint
    write_cef_format(results, siem_logger)
  File "./siem.py", line 316, in write_cef_format
    siem_logger.info(format_cef(flatten_json(i)) + u'\n')
  File "./siem.py", line 527, in format_cef
    value = format_extension(value)
  File "./siem.py", line 471, in format_extension
    return EXTENSION_PATTERN.sub(r'\\\1', data)
TypeError: expected string or buffer
```

I quick fixed with following code, but I'm not sure if the fix should actually be elsewhere in the code:

```
def format_extension(data):
    # equal sign and backslash in extension value must be escaped
    # escape group with backslash
    if not isinstance(data, unicode):
        return EXTENSION_PATTERN.sub(r'\\\1', str(data).encode('utf8'))
    return EXTENSION_PATTERN.sub(r'\\\1', data)
```

**Comment by rkamat** [comment]
@srinathman, we don't believe this is an issue with v2 of the tool.
