### ISSUE TITLE
Problem running siem.py as Windows scheduled task

### ISSUE THREAD

**Issue by papapelon** [sophos/Sophos-Central-SIEM-Integration#32]
I'm having trouble running this Python script from within a batch file that is set to run through a Windows scheduled task. If I run the script from the command line [python siem.py] it runs without issue. I am trying to set this up to run once every hour via Windows Task Scheduler. I created a batch file with the following syntax:

"C:\Users\redacted\AppData\Local\Programs\Python\Python37-32\python.exe" "c:\SophosSIEM\siem.py"

Here is the output that I receive when I run the batch file:

C:\Scripts>"C:\Users\redacted\AppData\Local\Programs\Python\Python37-32\python.ex
e" "c:\SophosSIEM\siem.py"
Traceback (most recent call last):
  File "c:\SophosSIEM\siem.py", line 494, in <module>
    main()
  File "c:\SophosSIEM\siem.py", line 173, in main
    token = config.Token(cfg.token_info)
  File "c:\SophosSIEM\config.py", line 34, in __getattr__
    return self.config.get('login', name)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python37-32\lib\configpar
ser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "C:\Users\redacted\AppData\Local\Programs\Python\Python37-32\lib\configpar
ser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'login'

I saw another issue someone reported that looked similar to this where there was a problem with the "login" section. Again, if I run the siem.py script manually, it works without issue. It is only when I try to run it in a batch file that my problems arise. Has anyone gotten this script to run successfully in a Windows environment using Task Scheduler? I'm not married to Batch scripting if someone has another scripting recommendation.

**Comment by papapelon** [comment]
I copied all components of the SIEM script into the Python program directory then was able to run the siem.py script successfully using any script or automation tool.
