### ISSUE TITLE
SSL Problems?

### ISSUE THREAD

**Issue by OldWindowsGuy** [sophos/Sophos-Central-SIEM-Integration#93]
Hi,

I want to connect "Sophos Central" to our SIEM (Rapid7). The script should run on a Windows 2022 server (one of the Sophos relay servers in our network). Python 3.13 is installed including OpenSSL 3.0.15. However, I have to admit that I have no idea about Python. So I'm a bit lost.

I followed the instructions and adjusted the "config.ini" (see attachment) accordingly. The script runs, but error messages appear (I have obscured the API data in the output below). Where did I make the mistake?

```
C:\Program Files\Rapid7\Sophos Integration\Sophos-Central-SIEM-Integration-2.1.0>py siem.py -d
Sophos state file not found
Config endpoint=/siem/v1/events, filename='result.txt' and format='json'
Fetching the tenants/customers list by calling the Sophos Cental API
fetching access_token from sophos
body :: {'grant_type': 'client_credentials', 'scope': 'token', 'client_id': 'xxxxxxxxxxxxxxxxxxxxxxxx', 'client_secret': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'}
Error :: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)>
JWT token not found for client id :: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Error :: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)>
Traceback (most recent call last):
  File "C:\Program Files\Rapid7\Sophos Integration\Sophos-Central-SIEM-Integration-2.1.0\siem.py", line 413, in <module>
    main()
    ~~~~^^
  File "C:\Program Files\Rapid7\Sophos Integration\Sophos-Central-SIEM-Integration-2.1.0\siem.py", line 410, in main
    run(options, config_data, state_data)
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Rapid7\Sophos Integration\Sophos-Central-SIEM-Integration-2.1.0\siem.py", line 401, in run
    get_alerts_or_events(
    ~~~~~~~~~~~~~~~~~~~~^
        endpoint, options, config_data, state
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Program Files\Rapid7\Sophos Integration\Sophos-Central-SIEM-Integration-2.1.0\siem.py", line 376, in get_alerts_or_events
    results = api_client_obj.get_alerts_or_events()
  File "C:\Program Files\Rapid7\Sophos Integration\Sophos-Central-SIEM-Integration-2.1.0\api_client.py", line 241, in get_alerts_or_events
    raise Exception(tenant_obj["error"])
Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)>
```
[config_ini_obscured.log](https://github.com/user-attachments/files/17948188/config_ini_obscured.log)

**Comment by TBJDevops** [comment]
Hi,

Good news first: this isn't your config or your Python. The script is doing exactly what it should and refusing to continue.

## What's actually happening

The failure is on the very first step. The script calls `https://id.sophos.com/...` to get an access token, and Python rejects the TLS certificate it's handed back. The specific message tells you why:

```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical
```

That message means the certificate Python received was **not** Sophos's real one. It was re-signed on the fly by something in your network path that inspects HTTPS traffic: a firewall doing SSL/TLS inspection, a web proxy, or an endpoint security product. Sophos's genuine certificate comes from a public authority and is correctly formed, so a malformed CA like this can only be a local interception certificate.

## Why it's failing now

Two things combine:

1. **The intercepting device's internal CA is built slightly out of spec.** It doesn't mark its "Basic Constraints" field as *critical*, which the X.509 standard requires for a CA cert. This is very common with appliance-generated CAs (Zscaler, pfSense, various firewalls all do it).
2. **Python 3.13 enforces strict certificate checking by default.** As of 3.13 the default SSL settings turned on `VERIFY_X509_STRICT`, which rejects malformed or pre-standard certificates that older Python versions quietly accepted. The same setup would very likely have worked on Python 3.12 or earlier.

This is also why browsers and other tools on the same box don't complain: they're more lenient, or they trust the interception CA through the Windows certificate store, which Python does **not** use by default.

## The fix (recommended)

Exclude the Sophos API endpoints from TLS/SSL inspection on whatever device is doing it. Ask whoever runs your firewall or proxy to add a decryption bypass / exception for:

- `id.sophos.com`
- `api.central.sophos.com`
- `*.central.sophos.com` (regional data hosts, e.g. `api-eu01.central.sophos.com`)

Once that traffic isn't intercepted, Python sees Sophos's real, publicly trusted certificate and the script works with no changes to your config or to Python. This is also the right call on security grounds: this connection carries your client secret and pulls your security event data, so it's exactly the traffic you least want a middlebox decrypting.

## If that traffic must stay inspected

More work, but possible:

- The interception CA has to be reissued with Basic Constraints marked *critical*, and
- that corrected CA must be made available to Python. Python on Windows doesn't read the Windows certificate store, so the CA needs to go into Python's own trust store via the `SSL_CERT_FILE` environment variable or by adding it to certifi's bundle.

On Python 3.13 the certificate genuinely has to be fixed; simply trusting the malformed one isn't enough, because strict mode will still reject it. Downgrading to Python 3.12 is what would make the old-style cert work again, but I wouldn't recommend solving it that way.

## What not to do

You'll find advice online to disable certificate verification or turn off the strict flag to make the error disappear. Don't do that here. It would leave the channel carrying your API credentials open to interception, which defeats the point of the integration.

## One security item to action

Your debug output included this line:

```
body :: {'grant_type': ..., 'client_secret': '...'}
```

In the 2.1.0 release the request body is logged in full when you run with `-d`, so your real client secret was written to the console on that run. You masked it before sharing, which is good, but if that output was captured anywhere unmasked (a log file, a screen share, a ticket), treat the secret as exposed and rotate it in Sophos Central. Either way, once this is working, drop the `-d` flag so it isn't logged again.
