### ISSUE TITLE
Error to send syslog - Wazuh

### ISSUE THREAD

**Issue by ccesario** [sophos/Sophos-Central-SIEM-Integration#94]
Hello dear, 

Im facing problem to send events/alert do Wazuh Syslog collecttor, ti following details about environtment.

$ cat config.ini
```
[login]
# API Access URL + Headers
# API token setup steps: https://community.sophos.com/kb/en-us/125169
token_info = <Copy API Access URL + Headers block from Sophos Central here>


# Client ID and Client Secret for Partners, Organizations and Tenants
# <Copy Client ID and Client Secret from Sophos Central here>
client_id = XXXXXXXXXXXX
client_secret = XXXXXXXXX
# Customer tenant Id
tenant_id = XXXXXXXXXXXXX


# Host URL for Oauth token
auth_url = https://id.sophos.com/api/v2/oauth2/token

# whoami API host url
api_host = api.central.sophos.com

# format can be json, cef or keyvalue
format = json

# filename can be syslog, stdout, any custom filename
filename = syslog

# endpoint can be event, alert or all
endpoint = event

# syslog properties
# for remote address use <remoteServerIp>:<port>, for e.g. 192.1.2.3:514
# for linux local systems use /dev/log
# for MAC OSX use /var/run/syslog
# append_nul will append null at the end of log message if set to true
#address = /var/run/syslog
address = 192.XX.XX.118:514
facility = daemon
socktype = tcp
append_nul = false

# cache file full or relative path (with a ".json" extension)
state_file_path = state/siem_sophos.json

# Delay the data collection by X minute to avoid events missing issue from Sophos API
# The issue could be due to some specific host being ahead in time for a few minute and Sophos Central would consider events received from that host as a checkpoint.
events_from_date_offset_minutes = 0

# Delay the data collection by X minute.
alerts_from_date_offset_minutes = 0

# Convert the dhost field to valid fqdn.
convert_dhost_field_to_valid_fqdn = true


#logging level
logging_level = DEBUG
```

$ python3 siem.py --debug  ( I got a several errors)
```
  SIEM_LOGGER.info(json.dumps(i, ensure_ascii=False).strip())
Message: '{"type": "Event::Firewall::FirewallAdvancedThreatProtectionDetailed", "severity": "medium", "source_info": {}, "customer_id": "YYYYYYYYYYYYYYYYY", "id": "5172a09e-0214-430f-ab39-8d4afb9ee83d", "group": "SECURITY", "name": "We detected an attempt to communicate with threat or botnet C2/Generic-A, from source 10.64.0.88 to destination vihansoft.ir(208.67.222.222).", "datastream": "event", "rt": "2024-12-26T03:32:25.493Z", "end": "2024-12-26T03:32:25.485Z", "dhost": "XXXX"}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 995, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 426, in <module>
    main()
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 423, in main
    run(options, config_data, state_data)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 403, in run
    get_alerts_or_events(
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 381, in get_alerts_or_events
    write_json_format(results, config)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 93, in write_json_format
    SIEM_LOGGER.info(json.dumps(i, ensure_ascii=False).strip())
Message: '{"type": "Event::Firewall::FirewallAdvancedThreatProtectionDetailed", "severity": "medium", "source_info": {}, "customer_id": "YYYYYYYYYYYYYYYYY", "id": "d7724e42-c6e8-437f-9cda-47f580b6077d", "group": "SECURITY", "name": "We detected an attempt to communicate with threat or botnet C2/Generic-A, from source 10.64.0.87 to destination vihansoft.ir(208.67.222.222).", "datastream": "event", "rt": "2024-12-26T03:32:28.266Z", "end": "2024-12-26T03:32:28.256Z", "dhost": "XXXX"}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 995, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 426, in <module>
    main()
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 423, in main
    run(options, config_data, state_data)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 403, in run
    get_alerts_or_events(
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 381, in get_alerts_or_events
    write_json_format(results, config)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 93, in write_json_format
    SIEM_LOGGER.info(json.dumps(i, ensure_ascii=False).strip())
Message: '{"type": "Event::Firewall::FirewallAdvancedThreatProtectionDetailed", "severity": "medium", "source_info": {}, "customer_id": "YYYYYYYYYYYYYYYYY", "id": "b71dadac-171e-4f52-94bf-c6f80fabd712", "group": "SECURITY", "name": "We detected an attempt to communicate with threat or botnet C2/Generic-A, from source 10.64.0.88 to destination vihansoft.ir(8.8.8.8).", "datastream": "event", "rt": "2024-12-26T03:32:30.846Z", "end": "2024-12-26T03:32:30.836Z", "dhost": "XXXX"}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 995, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 426, in <module>
    main()
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 423, in main
    run(options, config_data, state_data)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 403, in run
    get_alerts_or_events(
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 381, in get_alerts_or_events
    write_json_format(results, config)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 93, in write_json_format
    SIEM_LOGGER.info(json.dumps(i, ensure_ascii=False).strip())
Message: '{"type": "Event::Firewall::FirewallAdvancedThreatProtectionDetailed", "severity": "medium", "source_info": {}, "customer_id": "YYYYYYYYYYYYYYYYY", "id": "d3d8c276-072b-45de-ba18-8a29fcca89c0", "group": "SECURITY", "name": "We detected an attempt to communicate with threat or botnet C2/Generic-A, from source 10.64.0.87 to destination vihansoft.ir(8.8.8.8).", "datastream": "event", "rt": "2024-12-26T03:32:31.882Z", "end": "2024-12-26T03:32:31.875Z", "dhost": "XXXX"}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 995, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 426, in <module>
    main()
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 423, in main
    run(options, config_data, state_data)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 403, in run
    get_alerts_or_events(
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 381, in get_alerts_or_events
    write_json_format(results, config)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 93, in write_json_format
    SIEM_LOGGER.info(json.dumps(i, ensure_ascii=False).strip())
Message: '{"type": "Event::Firewall::FirewallAdvancedThreatProtectionDetailed", "severity": "medium", "source_info": {}, "customer_id": "YYYYYYYYYYYYYYYYY", "id": "f094da51-cbd5-4d4a-b1c2-fce026f7ad16", "group": "SECURITY", "name": "We detected an attempt to communicate with threat or botnet C2/Generic-A, from source 192.168.0.35 to destination http://differentia.ru/diff.php(184.105.192.2).", "datastream": "event", "rt": "2024-12-26T03:32:51.110Z", "end": "2024-12-26T03:32:51.103Z", "dhost": "XXXX"}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 995, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 426, in <module>
    main()
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 423, in main
    run(options, config_data, state_data)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 403, in run
    get_alerts_or_events(
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 381, in get_alerts_or_events
    write_json_format(results, config)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 93, in write_json_format
    SIEM_LOGGER.info(json.dumps(i, ensure_ascii=False).strip())
Message: '{"type": "Event::Firewall::FirewallAdvancedThreatProtectionDetailed", "severity": "medium", "source_info": {}, "customer_id": "YYYYYYYYYYYYYYYYY", "id": "03aa39c9-6f8f-4f3f-9aa0-37f82abd34e2", "group": "SECURITY", "name": "We detected an attempt to communicate with threat or botnet C2/Generic-A, from source 177.1.1.166 to destination http://differentia.ru/diff.php(18.143.144.165).", "datastream": "event", "rt": "2024-12-26T03:32:52.275Z", "end": "2024-12-26T03:32:52.269Z", "dhost": "utm-ame-ara-atuba"}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 995, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 426, in <module>
    main()
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 423, in main
    run(options, config_data, state_data)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 403, in run
    get_alerts_or_events(
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 381, in get_alerts_or_events
    write_json_format(results, config)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 93, in write_json_format
    SIEM_LOGGER.info(json.dumps(i, ensure_ascii=False).strip())
Message: '{"type": "Event::Firewall::FirewallAdvancedThreatProtectionDetailed", "severity": "medium", "source_info": {}, "customer_id": "YYYYYYYYYYYYYYYYY", "id": "d2bd8a69-2877-4b1a-ace7-566a0aca6d53", "group": "SECURITY", "name": "We detected an attempt to communicate with threat or botnet C2/Generic-A, from source 10.64.0.87 to destination vihansoft.ir(1.1.1.1).", "datastream": "event", "rt": "2024-12-26T03:33:36.602Z", "end": "2024-12-26T03:33:36.588Z", "dhost": "XXXX"}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 995, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 426, in <module>
    main()
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 423, in main
    run(options, config_data, state_data)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 403, in run
    get_alerts_or_events(
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 381, in get_alerts_or_events
    write_json_format(results, config)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 93, in write_json_format
    SIEM_LOGGER.info(json.dumps(i, ensure_ascii=False).strip())
Message: '{"type": "Event::Firewall::FirewallAdvancedThreatProtectionDetailed", "severity": "medium", "source_info": {}, "customer_id": "YYYYYYYYYYYYYYYYY", "id": "24cfd607-5db0-40e9-9835-e1f91bba9d69", "group": "SECURITY", "name": "We detected an attempt to communicate with threat or botnet C2/Generic-A, from source 10.64.0.88 to destination vihansoft.ir(208.67.222.222).", "datastream": "event", "rt": "2024-12-26T03:33:37.608Z", "end": "2024-12-26T03:33:37.599Z", "dhost": "XXXX"}'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/handlers.py", line 995, in emit
    self.socket.sendall(msg)
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 426, in <module>
    main()
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 423, in main
    run(options, config_data, state_data)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 403, in run
    get_alerts_or_events(
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 381, in get_alerts_or_events
    write_json_format(results, config)
  File "/tmp/Sophos-Central-SIEM-Integration/siem.py", line 93, in write_json_format
    SIEM_LOGGER.info(json.dumps(i, ensure_ascii=False).strip())
Message: '{"type": "Event::Firewall::FirewallAdvancedThreatProtectionDetailed", "severity": "medium", "source_info": {}, "customer_id": "YYYYYYYYYYYYYYYYY", "id": "101fcee9-7eee-49da-8a4a-3af43bf9da37", "group": "SECURITY", "name": "We detected an attempt to communicate with threat or botnet C2/Generic-A, from source 10.64.0.87 to destination vihansoft.ir(208.67.222.222).", "datastream": "event", "rt": "2024-12-26T03:33:39.937Z", "end": "2024-12-26T03:33:39.927Z", "dhost": "XXXX"}'
Arguments: ()
```

**Comment by TBJDevops** [comment]
## Summary

The errors aren't a Sophos or data problem. Every event was fetched and serialised fine (the full JSON is right there in each message). The crash is purely on delivery: `BrokenPipeError [Errno 32]` on `socket.sendall` means the TCP connection to the Wazuh collector on `192.XX.XX.118:514` came up, then the receiver closed/reset it, and the script kept writing into a dead socket.

It floods on every event because Python's `SysLogHandler` opens one TCP socket at startup and never reconnects, so a single drop repeats for the whole run.

The error is diagnostic: it's not "can't connect" (that fails differently and the startup check would have caught it). The handshake succeeds, then the peer drops it.

## Most likely causes (in order)

1. **Wazuh `<allowed-ips>` doesn't include the collector's source IP.** `wazuh-remoted` accepts the TCP handshake then rejects on source validation, which looks exactly like a broken pipe. The startup check doesn't catch this because it never writes to the socket.
2. **Protocol/listener mismatch** in the `<remote>` block. Needs `connection=syslog`, `protocol=tcp`, on 514 (not the agent listener on 1514).
3. **Firewall/NAT/LB sending an RST**, or something other than Wazuh syslog on 514.

## Checks on the Wazuh manager

- `ss -lntp | grep 514` - confirm `wazuh-remoted` owns a TCP socket there.
- Review the `<remote>` block in `ossec.conf`, especially `allowed-ips`; add the collector IP/CIDR if missing and restart.
- Tail `ossec.log` while running `siem.py` and watch for rejection / "not in allowed-ips" lines.
- Test the path independently: `echo "<13>sophos-test" | nc 192.XX.XX.118 514`. If `nc` also drops, it's Wazuh/network config, not the script.

## Side notes

- **Interim fix:** point `filename` at a local file and tail it with the Wazuh agent. This avoids the no-reconnect syslog handler entirely and is more robust for a security feed.
- **Security:** drop `logging_level` back to `INFO` and remove `--debug` once working - debug mode dumps your `Authorization` and `x-api-key` headers to stderr.Sophos wazuh brokenpipeDocument · MD Download
